apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b9jn7h4pt-python
  janus-idp.io/tekton: b9jn7h4pt-python
  backstage.io/kubernetes-id: b9jn7h4pt-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b9jn7h4pt-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
